### PR TITLE
Shutdown eahub

### PR DESCRIPTION
**Pull request by lwasser**
we can restart it again in august
also made some minor doc edits here just for the future.

The one piece i'm still struggling with is that travis user being my local user. i can't seem to get rid of it. but otherwise the hub is GONE as is all storage and this PR can be merged i think!

### CODE REVIEW

**Comment by lwasser** [comment]
@kcranston  i'm running through the shutdown hub docs

[here](https://earthlab-hub-ops.readthedocs.io/en/latest/daily-operations/modify-remove-hub.html#step-two-uninstall-the-helm-release) it suggests that two pods should be running but i actually see this:

Screen Shot 2020-07-15 at 4 53 28 PM

Does this make sense to you? i just want to update things in the docs if they are not correct. thank you!

**Comment by lwasser** [comment]
me again -- because of that travis user i'm having issues running this locally - did you document how to revert back to ME as a user vs the travis user locally? maybe when we meet next we you can help me and i can document it for future?

**Comment by lwasser** [comment]
i do think i managed to shut down the hub tho!!

**Comment by kcranston** [comment]
This looks good to me, and it appears that the hub is no longer running. I'll put in a separate PR with some doc changes for the travis user and the chart list.

**Comment by lwasser** [comment]
yay - thank you @kcranston i am so happy we are spending this time on documentation. it's really been helpful. especially for these tasks that are not done often.

**Pull request merged**
