### PR TITLE
Update homework template repo for EA Bootcamp in ea-hub/values.yaml

### LINKED ISSUE #175: Please create a repo that you'd like to use for the ea-hub
hey @jlpalomino 

https://github.com/earthlab/hub-ops/blob/master/hub-charts/ea-hub/values.yaml#L40

this line in my merged PR was the one i was waitin to update. can you please create a new repo that you'd like to use and submit a PR that simply updates the link to link to the new public repo? conversely you can send me the link, and i can make the update. but we need to do this tomorrow as what is happening now is the old repo will be added to students pods!! i'm not sure how it will go if we change the repo name - but i suggest changing it and creating a new folder - maybe ea-lessons or ea-homework-notebooks or whatever you want to call it.

### PR DESCRIPTION
**Pull request by jlpalomino**
@lwasser This PR updates the repository and directory name for the homework template. The repository is a public repository created to get the homework templates onto the hub.  Fixes #175

### CODE REVIEW

**Comment by lwasser** [comment]
awesome. thank you @jlpalomino  this looks great. i'll merge. let's see if that directory appears when you login to the hub. i'm not sure how long it might take to build - perhaps 1-2 hours?

**Comment by lwasser** [comment]
ok the homework templates dir is there now. but i dont' see that any students have the hub up and running so perhaps we can make this fix before they login and see the other directory!! :)

**Comment by lwasser** [comment]
oh never mind. they have logged in. a few of them may have that homework-templates dir. once the hub updates ill test and see what happens as i have it now too.

**Comment by jlpalomino** [comment]
I logged in as ea-student, and I see the new directory `ea-homework-notebooks` (not the old one but of course, I wasn't logged in before).  I'll make a note for Friday to go over how to delete that old directory.

**Comment by lwasser** [comment]
awesome. yes i would expect you wouldn't see both if you hadn't logged in after that PR!!  it's a good test of their bash skills too to delete ... use the `-rf` flag and such... :) thanks @jlpalomino luckily most students did NOT login over the weekend. a few did however.

**Pull request merged**
